// Mostrando nosso Level
draw_set_font(fnt_exibir);

draw_text(70, 20, "Level: " + string(global.level)); // Mostrando nosso Level...
draw_text(70, 40, "XP: " + string(expa)); // Mostrando XP atual...
draw_text(80, 60, "XP necessario: " + string(expn - expa)); // Mostrando quanto falta para o próximo level...
